### PR TITLE
fix: parse heroku api messages

### PR DESCRIPTION
**Pull request by bronislav**
I tried to get scaling message reporting work and after long time tries and error, I found that we are expecting the wrong header. 

From what I see, scaling messages appears in logs under "host app api" and not "host heroku api" as we are expecting.

So, I've fixed this add a few more specs.

### CODE REVIEW

**Comment by abtris** [comment]
Looks good to me. After tests and review passed we can merge.

**Comment by w-vi** [comment]
Seems that tests enter some infinite loop. Otherwise it looks good.

**Review by w-vi — CHANGES_REQUESTED** [review]
Fix tests

**Comment by bronislav** [comment]
@w-vi @abtris Thank you for your comments.

**Comment by abtris** [comment]
Closing, need rebase and maybe fixed in others PR.

**Pull request closed without merging**
