### PR TITLE
Fixing the scale events support

### PR DESCRIPTION
**Pull request by kubek2k**
this should be compliant with current format of heroku loglines regarding scaling

replaces https://github.com/apiaryio/heroku-datadog-drain-golang/pull/44

### CODE REVIEW

**Comment by w-vi** [comment]
Thanks for the contribution. How is this related to changes in #48? From a quick look it seems they are related.

**Comment by kubek2k** [comment]
> How is this related to changes in #48? From a quick look it seems they are related.

Both are parsing the app/api messages, but this one is for interpreting Scaling messages, the other is sending out release event.

**Comment by abtris** [comment]
Pls rebase with actual master

**Comment by kubek2k** [comment]
@abtris should be ok now

**Pull request merged**
