### PR TITLE
feat: add support for multistage builds

### PR DESCRIPTION
**Pull request by abtris**

### CODE REVIEW

**Review by w-vi — APPROVED** [review]

**Comment by abtris** [comment]
Need rebase

**Comment by abtris** [comment]
@w-vi pls make review again, multi changes during rebase

**Review by w-vi — CHANGES_REQUESTED** [review]
Keep the FROM part but the ADD is actually correct in the original.

**Comment by abtris** [comment]
@w-vi fixed, removed ADD part.

**Review by w-vi — APPROVED** [review]

**Pull request merged**
