### PR TITLE
Update to golang 1.6

### PR DESCRIPTION
**Pull request by abtris**
- remove Godeps folder
- migrate to vendor
- using Glide instead Godep
- add Dockerfile to test build

### CODE REVIEW

**Comment by abtris** [comment]
@w-vi can you check if upgrade is ok?

**Comment by abtris** [comment]
@w-vi failed test:

```
GIN-debug] POST   /                         --> github.com/apiaryio/heroku-datadog-drain-golang.(*ServerCtx).(github.com/apiaryio/heroku-datadog-drain-golang.processLogs)-fm (2 handlers)
--- FAIL: TestFull (1.00s)
    server_test.go:180: Expected: app.metric.request.length:541.000000|h|#source:web.1,route:/parser,request.id:11747467-f4ce-4b06-8c99-92be968a02e3. Actual: app.metric.request.length:541.000000|h|#source:web.1,request.id:11747467-f4ce-4b06-8c99-92be968a02e3,route:/parser
    server_test.go:180: Expected: app.metric.response.length:5163.000000|h|#source:web.1,route:/parser,request.id:11747467-f4ce-4b06-8c99-92be968a02e3. Actual: app.metric.response.length:5163.000000|h|#source:web.1,request.id:11747467-f4ce-4b06-8c99-92be968a02e3,route:/parser
    server_test.go:180: Expected: app.metric.parser.time:5.000000|h|#source:web.1,route:/parser,request.id:11747467-f4ce-4b06-8c99-92be968a02e3. Actual: app.metric.parser.time:5.000000|h|#source:web.1,request.id:11747467-f4ce-4b06-8c99-92be968a02e3,route:/parser
FAIL
exit status 1
```

it's problem with request order to compare tests. Suggestion how fix this?

**Comment by w-vi** [comment]
@abtris I knew that this will blow to our face one day, it was relying on the hash table implementation. I will fix it, have to figure out how though.

**Comment by abtris** [comment]
@w-vi can be possible using https://golang.org/pkg/reflect/#DeepEqual for compare arrays?

**Comment by abtris** [comment]
I make more debugging and find problem not only order in testing but order in processing request isn't for tests ideal.

```
MESSAGE_: app.metric.parser.time:5.000000|h|#source:web.1,request.id:11747467-f4ce-4b06-8c99-92be968a02e3,route:/parser
TESTED__: app.metric.request.length:541.000000|h|#source:web.1,route:/parser,request.id:11747467-f4ce-4b06-8c99-92be968a02e3
TESTED__: app.metric.response.length:5163.000000|h|#source:web.1,route:/parser,request.id:11747467-f4ce-4b06-8c99-92be968a02e3
TESTED__: app.metric.parser.time:5.000000|h|#source:web.1,route:/parser,request.id:11747467-f4ce-4b06-8c99-92be968a02e3
```

but I'm not sure if is real problem. For `statsd` isn't problem changing parameters order problem is only string equality in tests.

**Comment by w-vi** [comment]
Cool, I was going to do this, because order doesn't matter. So all is good again :)

**Pull request merged**
