### PR TITLE
Docker automatically unpacks retrieved files

### PR DESCRIPTION
**Pull request by kubek2k**
this fixes build for Docker version 17.06.0-ce-mac19

### CODE REVIEW

**Comment by w-vi** [comment]
Thanks a lot. Apparently we are not using the docker image as we would've caught it :)

**Comment by w-vi** [comment]
@abtris Can you merge please? It looks like I don't have write access.

**Comment by kubek2k** [comment]
> Thanks a lot. Apparently we are not using the docker image as we would've caught it :)

I did because my local installation of go was broken, and had to run `go test` somehow ;)

**Comment by abtris** [comment]
@w-vi fixed your access

**Pull request merged**
